-- MySQL Script generated by MySQL Workbench
-- lun 09 sep 2019 22:33:02 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema KRONOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KRONOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KRONOS` DEFAULT CHARACTER SET utf8 ;
USE `KRONOS` ;

-- -----------------------------------------------------
-- Table `KRONOS`.`T_ACT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_ACT` (
  `ACTNUMBER` VARCHAR(100) NOT NULL,
  `SESSIONTYPE` VARCHAR(100) NULL,
  `DATE` DATE NULL,
  `PDF` VARCHAR(100) NULL,
  `PUBLIC` TINYINT NULL,
  `ACTIVE` TINYINT NULL,
  PRIMARY KEY (`ACTNUMBER`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_DEPARTMENT` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_TEMPUSER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_TEMPUSER` (
  `ID` VARCHAR(100) NOT NULL,
  `NAME` VARCHAR(100) NULL,
  `EMAIL` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_USER` (
  `DEPARTMENT` INT NOT NULL,
  `TEMPUSER` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(45) NULL,
  INDEX `fk_T_USER_T_DEPARTMENT1_idx` (`DEPARTMENT` ASC),
  INDEX `fk_T_USER_T_TEMPUSER1_idx` (`TEMPUSER` ASC),
  PRIMARY KEY (`TEMPUSER`),
  CONSTRAINT `fk_T_USER_T_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT`)
    REFERENCES `KRONOS`.`T_DEPARTMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_USER_T_TEMPUSER1`
    FOREIGN KEY (`TEMPUSER`)
    REFERENCES `KRONOS`.`T_TEMPUSER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_ACCORD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_ACCORD` (
  `ACCNUMBER` VARCHAR(100) NOT NULL,
  `INCORDATE` DATE NULL,
  `DEADLINE` DATE NULL,
  `ACTNUMBER` VARCHAR(100) NULL,
  `SESSIONDATE` VARCHAR(100) NOT NULL,
  `TYPE` VARCHAR(100) NULL,
  `OBSERVATIONS` LONGTEXT NULL,
  `PUBLIC` TINYINT NULL,
  `NOTIFIED` TINYINT NULL,
  `STATE` CHAR(1) NULL,
  `OFFICE` VARCHAR(45) NULL,
  INDEX `fk_T_ACCORD_T_ACT_idx` (`ACTNUMBER` ASC),
  PRIMARY KEY (`ACCNUMBER`),
  INDEX `fk_T_ACCORD_T_USER1_idx` (`SESSIONDATE` ASC),
  CONSTRAINT `fk_T_ACCORD_T_ACT`
    FOREIGN KEY (`ACTNUMBER`)
    REFERENCES `KRONOS`.`T_ACT` (`ACTNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ACCORD_T_USER1`
    FOREIGN KEY (`SESSIONDATE`)
    REFERENCES `KRONOS`.`T_USER` (`TEMPUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_ROLE` (
  `USERID` VARCHAR(100) NOT NULL,
  `ROLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USERID`, `ROLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_NOTIFICATION` (
  `ACCORD` VARCHAR(100) NOT NULL,
  `USER` VARCHAR(100) NOT NULL,
  INDEX `fk_T_NOTIFICATION_T_ACCORD1_idx` (`ACCORD` ASC),
  PRIMARY KEY (`ACCORD`, `USER`),
  INDEX `fk_T_NOTIFICATION_T_USER1_idx` (`USER` ASC),
  CONSTRAINT `fk_T_NOTIFICATION_T_ACCORD1`
    FOREIGN KEY (`ACCORD`)
    REFERENCES `KRONOS`.`T_ACCORD` (`ACCNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NOTIFICATION_T_USER1`
    FOREIGN KEY (`USER`)
    REFERENCES `KRONOS`.`T_USER` (`TEMPUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_USERACC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_USERACC` (
  `TEMPUSER` VARCHAR(100) NOT NULL,
  `ACCORD` VARCHAR(100) NOT NULL,
  INDEX `fk_T_USERACC_T_TEMPUSER1_idx` (`TEMPUSER` ASC),
  INDEX `fk_T_USERACC_T_ACCORD1_idx` (`ACCORD` ASC),
  PRIMARY KEY (`TEMPUSER`, `ACCORD`),
  CONSTRAINT `fk_T_USERACC_T_TEMPUSER1`
    FOREIGN KEY (`TEMPUSER`)
    REFERENCES `KRONOS`.`T_TEMPUSER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_USERACC_T_ACCORD1`
    FOREIGN KEY (`ACCORD`)
    REFERENCES `KRONOS`.`T_ACCORD` (`ACCNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_ACCPDF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_ACCPDF` (
  `ACCORD` VARCHAR(100) NOT NULL,
  `PDF` VARCHAR(100) NULL,
  INDEX `fk_T_ACCPDF_T_ACCORD1_idx` (`ACCORD` ASC),
  CONSTRAINT `fk_T_ACCPDF_T_ACCORD1`
    FOREIGN KEY (`ACCORD`)
    REFERENCES `KRONOS`.`T_ACCORD` (`ACCNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KRONOS`.`T_ACCRESPONSABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KRONOS`.`T_ACCRESPONSABLE` (
  `T_ACCORD_ACCNUMBER` VARCHAR(100) NOT NULL,
  `RESPONSABLE` VARCHAR(100) NULL,
  INDEX `fk_T_ACCRESPON_T_ACCORD1_idx` (`T_ACCORD_ACCNUMBER` ASC),
  CONSTRAINT `fk_T_ACCRESPON_T_ACCORD1`
    FOREIGN KEY (`T_ACCORD_ACCNUMBER`)
    REFERENCES `KRONOS`.`T_ACCORD` (`ACCNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
